import Head from 'next/head'
import MainBar from '../components/MainBar'
import SideBar from '../components/SideBar'
import { useSession } from "next-auth/react"

export default function Home() {
  const { data: session, status } = useSession()
console.log(session);
  return (
    <div>
      <Head>
        <title>Spotify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex overflow-hidden h-screen'>
      <SideBar />
      <MainBar />
      </div>

      
    </div>
  )
}
