import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spotify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-black text-white h-screen flex justify-center items-center '>
      hey
      </div>

      
    </div>
  )
}
